name: Inventory-Manager-Frontend

on:
  push:
    branches: [ master, week-* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
